/**
* assets.ts contains custom assets, and surfaces icons.get(name: string)
* This function allows you to get your assets, and the ones in user_interface_base
* It's done this way to make locallisation easier later on.
*/
namespace micro_ml {
  export class icons {
    public static get(name: string, nullIfMissing = false): Bitmap {
      if (name == "microMLLogo") return microMLLogo
      if (name == "tick") return tick

      return user_interface_base.icons.get(name, nullIfMissing);
    }
  }

  export const microMLLogo = bmp` 
    ....111111.......111111...1111.................................................111111.......111111...................
    ...11bbbbbb.....11bbbbbb.11bbbb...............................................11bbbbbb.....11bbbbbb....11............
    ...1bbbbbbbb...11bbbbbbbf1bbbbbf..............................................1bbbbbbbb...11bbbbbbbf.11bb1...........
    ...1bbbbbbbbb.11bbbbbbbbf1bbbbbf..............................................1bbbbbbbbb.11bbbbbbbbf1bbbbb1..........
    ...1bbbbbbbbbb1bbbbbbbbbf1bbbbbf..............................................1bbbbbbbbbb1bbbbbbbbbf1bbbbbb..........
    ...1bbbbbbbbbbbbbbbbbbbbf.bbbbff..............................................1bbbbbbbbbbbbbbbbbbbbf1bbbbbbf.........
    ...1bbbbbbbbbbbbbbbbbbbbf..ffff.....1111111......1111...111.......1111111.....1bbbbbbbbbbbbbbbbbbbbf1bbbbbbf.........
    ...1bbbbbbbbbbbbbbbbbbbbf.1111....111bbbbbbb1...11bbbb.11bbb....111bbbbbbb1...1bbbbbbbbbbbbbbbbbbbbf1bbbbbbf.........
    ...1bbbbbbbbbbbbbbbbbbbbf11bbbb..11bbbbbbbbbbb..1bbbbbb1bbbbb..11bbbbbbbbbbb..1bbbbbbbbbbbbbbbbbbbbf1bbbbbbf.........
    ...1bbbbbbfbbbbbfbbbbbbbf1bbbbbf.1bbbbbbbbbbbbf.1bbbbbbbbbbbbf.1bbbbbbbbbbbbf.1bbbbbbfbbbbbfbbbbbbbf1bbbbbbf.........
    ...1bbbbbbf.bbbff1bbbbbbf1bbbbbf11bbbbbbbbbbbbb.1bbbbbbbbbbbbf11bbbbbbbbbbbbb.1bbbbbbf.bbbff1bbbbbbf1bbbbbbf.........
    ...1bbbbbbf..fff.1bbbbbbf1bbbbbf1bbbbbfffbbbbbbf1bbbbbfffbbbff1bbbbbfffbbbbbbf1bbbbbbf..fff.1bbbbbbf1bbbbbbf.........
    ...1bbbbbbf......1bbbbbbf1bbbbbf1bbbbff...bbbbff1bbbbbf...fff.1bbbbff...bbbbbffbbbbbbf......1bbbbbbf1bbbbbbf.........
    ...1bbbbbbf......1bbbbbbf1bbbbbf1bbbbf.....ffff.1bbbbbf.......1bbbbf....1bbbbffbbbbbbf......1bbbbbbf1bbbbbbf.........
    ...1bbbbbbf......1bbbbbbf1bbbbbf1bbbbf....1111..1bbbbbf.......1bbbbf....1bbbbffbbbbbbf......1bbbbbbf1bbbbbbf.........
    ...1bbbbbbf......1bbbbbbf1bbbbbf1bbbbb...11bbbb.1bbbbbf.......1bbbbb...11bbbbffbbbbbbf......1bbbbbbf1bbbbbbffff......
    ...1bbbbbbf......1bbbbbbf1bbbbbf1bbbbbb111bbbbbf1bbbbbf.......1bbbbbb111bbbbbffbbbbbbf......1bbbbbbf1bbbbbbbbbbb.....
    ...1bbbbbbf......1bbbbbbf1bbbbbf.bbbbbbbbbbbbbff1bbbbbf........bbbbbbbbbbbbbfffbbbbbbf......1bbbbbbf1bbbbbbbbbbbbf...
    ...1bbbbbbf......1bbbbbbf1bbbbbf.1bbbbbbbbbbbbf.1bbbbbf........1bbbbbbbbbbbbf.fbbbbbbf......1bbbbbbffbbbbbbbbbbbbf...
    ...1bbbbbbf......1bbbbbbf1bbbbbf..bbbbbbbbbbbff.1bbbbbf.........bbbbbbbbbbbff.fbbbbbbf......1bbbbbbffbbbbbbbbbbbf....
    ....bbbbbff.......bbbbbff.bbbbff...fbbbbbbbfff...bbbbff..........fbbbbbbbfff...bbbbbff.......bbbbbff.fbbbbbbbbbff....
    .....fffff.........fffff...ffff......fffffff......ffff.............fffffff......fffff.........fffff...ffffffffff.....
`

  export const tick = bmp`
    ........................111.....
    .......................1777f....
    ......................17777f....
    .....................17777f.....
    ....................17777f......
    ...................17777f.......
    ..................17777f........
    ....111..........17777f.........
    ...17771........17777f..........
    ...177771......17777f...........
    ....f77771....17777f............
    .....f77771..17777f.............
    ......f7777117777f..............
    .......f77777777f...............
    ........f777777f................
    .........f7777f.................
    ..........ffff..................
    ................................
`
}
